name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargon/registry
        key: ${{ runner.os }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
