name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - nightly
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargon/registry
        key: ${{ runner.os }}-${{ matrix.rust-toolchain }}
    - name: Install Rust
      run: rustup install ${{ matrix.rust-toolchain }}
    - name: Build
      run: cargo +${{ matrix.rust-toolchain }} build --verbose
    - name: Run tests
      run: cargo +${{ matrix.rust-toolchain }} test --verbose
