name: CI
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cache Load
              uses: Swatinem/rust-cache@v1
            - name: Stable Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  components: rustfmt, clippy
            - name: Cargo Check
              uses: actions-rs/cargo@v1
              with:
                  command: check
            - name: Annotate commit with clippy warnings
              uses: actions-rs/clippy-check@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                args: --all-features
            - name: Security audit
              uses: actions-rs/audit-check@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Cargo Publish
              uses: actions-rs/cargo@v1
              with:
                  command: publish
                  args: ${{ secrets.CARGO_REGISTRY_TOKEN }}
