name: CI
on: [push, pull_request]

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        strategy:
        matrix:
            rust-toolchain:
                - stable
                - nightly
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cargo Cache
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargon/registry
                  key: ${{ runner.os }}-${{ matrix.rust-toolchain }}
            - name: Setup stable rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.rust-toolchain }}
                  components: rustfmt, clippy
            - name: Cargo Check
              uses: actions-rs/cargo@v1
              with:
                  command: check
            - name: Annotate commit with clippy warnings
              uses: actions-rs/clippy-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: --all-features
            - name: Security audit
              uses: actions-rs/audit-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
